/* =========================================================
   PROYECTO FRAMED
   Archivo: 01_creacion_tablas.sql
   Descripción: Creación de las tablas principales del sistema
   Motor: Oracle Database
   ========================================================= */


/* =========================================================
   1. CATÁLOGO DE DIRECTORES TÉCNICOS
   ========================================================= */

CREATE TABLE DT (
    ID_DT           NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE          VARCHAR2(150) NOT NULL,
    DOCUMENTO       VARCHAR2(30),
    TELEFONO        VARCHAR2(30),
    CORREO          VARCHAR2(150),
    ESTADO          VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT PK_DT PRIMARY KEY (ID_DT)
);


/* =========================================================
   2. MUNICIPIOS
   ========================================================= */

CREATE TABLE MUNICIPIOS (
    ID_MUNICIPIO    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE          VARCHAR2(100) NOT NULL,
    REGION          VARCHAR2(100),
    CODIGO_DANE     VARCHAR2(10),

    CONSTRAINT PK_MUNICIPIOS PRIMARY KEY (ID_MUNICIPIO),
    CONSTRAINT UK_MUNICIPIOS_NOMBRE UNIQUE (NOMBRE)
);


/* =========================================================
   3. ESTADOS DE LOS ESTABLECIMIENTOS
   ========================================================= */

CREATE TABLE ESTADO (
    ID_ESTADO       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE          VARCHAR2(50) NOT NULL,
    DESCRIPCION     VARCHAR2(250),

    CONSTRAINT PK_ESTADO PRIMARY KEY (ID_ESTADO),
    CONSTRAINT UK_ESTADO_NOMBRE UNIQUE (NOMBRE)
);


/* =========================================================
   4. TIPOS DE NOVEDAD
   ========================================================= */

CREATE TABLE TIPO_NOVEDAD (
    ID_TIPO_NOVEDAD NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE          VARCHAR2(200) NOT NULL,

    CONSTRAINT PK_TIPO_NOVEDAD PRIMARY KEY (ID_TIPO_NOVEDAD),
    CONSTRAINT UK_TIPO_NOVEDAD_NOMBRE UNIQUE (NOMBRE)
);


/* =========================================================
   5. SERVICIOS
   ========================================================= */

CREATE TABLE SERVICIOS (
    ID_SERVICIO     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE          VARCHAR2(150) NOT NULL,
    DESCRIPCION     VARCHAR2(500),
    ESTADO          VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT PK_SERVICIOS PRIMARY KEY (ID_SERVICIO),
    CONSTRAINT UK_SERVICIOS_NOMBRE UNIQUE (NOMBRE)
);


/* =========================================================
   6. ESTABLECIMIENTOS FARMACÉUTICOS
   ========================================================= */

CREATE TABLE ESTABLECIMIENTO (
    ID_ESTABLECIMIENTO             NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE                         VARCHAR2(200) NOT NULL,
    RAZON_SOCIAL                   VARCHAR2(200),
    NIT                            VARCHAR2(20) NOT NULL,
    CODIGO_ESTABLECIMIENTO         VARCHAR2(30),
    MUNICIPIO                      NUMBER NOT NULL,
    DIRECCION                      VARCHAR2(250) NOT NULL,
    BARRIO                         VARCHAR2(100),
    TELEFONO                       VARCHAR2(30),
    EMAIL                          VARCHAR2(150),
    REPRESENTANTE_LEGAL            VARCHAR2(150),
    DOCUMENTO_REPRESENTANTE_LEGAL  VARCHAR2(30),
    MATRICULA_MERCANTIL            VARCHAR2(50),
    DIRECTOR_TECNICO               VARCHAR2(150),
    DOCUMENTO_DIRECTOR_TECNICO     VARCHAR2(30),
    ID_DT                          NUMBER,
    ESTADO                         VARCHAR2(20),
    ID_ESTADO                      NUMBER,
    ID_TIPO_ESTABLECIMIENTO        NUMBER,
    GRUPO                          VARCHAR2(100),
    REGION                         VARCHAR2(100),
    FECHA_REGISTRO                 DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_ESTABLECIMIENTO
        PRIMARY KEY (ID_ESTABLECIMIENTO),

    CONSTRAINT UK_ESTABLECIMIENTO_NIT
        UNIQUE (NIT),

    CONSTRAINT UK_ESTABLECIMIENTO_CODIGO
        UNIQUE (CODIGO_ESTABLECIMIENTO)
);


/* =========================================================
   7. RELACIÓN ENTRE ESTABLECIMIENTOS Y SERVICIOS
   ========================================================= */

CREATE TABLE ESTABLECIMIENTO_SERVICIO (
    ID_ESTABLECIMIENTO_SERVICIO NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_ESTABLECIMIENTO          NUMBER NOT NULL,
    ID_SERVICIO                 NUMBER NOT NULL,
    FECHA_REGISTRO              DATE DEFAULT SYSDATE NOT NULL,
    ESTADO                      VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,

    CONSTRAINT PK_ESTABLECIMIENTO_SERVICIO
        PRIMARY KEY (ID_ESTABLECIMIENTO_SERVICIO),

    CONSTRAINT UK_ESTABLECIMIENTO_SERVICIO
        UNIQUE (ID_ESTABLECIMIENTO, ID_SERVICIO)
);


/* =========================================================
   8. REPORTANTES
   ========================================================= */

CREATE TABLE REPORTANTE (
    ID_REPORTANTE    NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TIPO_DOCUMENTO   VARCHAR2(20),
    NUMERO_DOCUMENTO VARCHAR2(30),
    NOMBRE           VARCHAR2(150) NOT NULL,
    TELEFONO         VARCHAR2(30),
    CORREO           VARCHAR2(150),
    CARGO            VARCHAR2(100),
    ENTIDAD          VARCHAR2(150),
    FECHA_REGISTRO   DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_REPORTANTE PRIMARY KEY (ID_REPORTANTE)
);


/* =========================================================
   9. ESTADOS DE LOS REPORTES
   ========================================================= */

CREATE TABLE ESTADO_REPORTE (
    ID_ESTADO_REPORTE NUMBER GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE             VARCHAR2(50) NOT NULL,
    DESCRIPCION        VARCHAR2(250),

    CONSTRAINT PK_ESTADO_REPORTE PRIMARY KEY (ID_ESTADO_REPORTE),
    CONSTRAINT UK_ESTADO_REPORTE_NOMBRE UNIQUE (NOMBRE)
);


/* =========================================================
   10. REPORTES
   ========================================================= */

CREATE TABLE REPORTES (
    ID_REPORTE        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    RADICADO          VARCHAR2(30) NOT NULL,
    ID_ESTABLECIMIENTO NUMBER NOT NULL,
    ID_REPORTANTE     NUMBER NOT NULL,
    ID_ESTADO_REPORTE NUMBER NOT NULL,
    FECHA_REPORTE     DATE DEFAULT SYSDATE NOT NULL,
    OBSERVACIONES     VARCHAR2(1000),

    CONSTRAINT PK_REPORTES PRIMARY KEY (ID_REPORTE),
    CONSTRAINT UK_REPORTES_RADICADO UNIQUE (RADICADO)
);


/* =========================================================
   11. NOVEDADES
   ========================================================= */

CREATE TABLE NOVEDADES (
    ID_NOVEDAD          NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_REPORTE          NUMBER NOT NULL,
    ID_ESTABLECIMIENTO  NUMBER NOT NULL,
    ID_TIPO_NOVEDAD     NUMBER NOT NULL,
    DESCRIPCION         VARCHAR2(1000),
    ESTADO              VARCHAR2(20) DEFAULT 'REGISTRADA' NOT NULL,
    FECHA_REPORTE       DATE DEFAULT SYSDATE NOT NULL,
    USUARIO_REPORTA     VARCHAR2(150),

    CONSTRAINT PK_NOVEDADES PRIMARY KEY (ID_NOVEDAD)
);


/* =========================================================
   12. HISTORIAL DE CAMBIOS DE LOS REPORTES
   ========================================================= */

CREATE TABLE HISTORIAL_REPORTE (
    ID_HISTORIAL     NUMBER GENERATED BY DEFAULT AS IDENTITY,
    ID_REPORTE       NUMBER NOT NULL,
    FECHA_CAMBIO     DATE DEFAULT SYSDATE NOT NULL,
    ESTADO_ANTERIOR  VARCHAR2(50),
    ESTADO_NUEVO     VARCHAR2(50),
    OBSERVACION      VARCHAR2(1000),
    USUARIO          VARCHAR2(150),

    CONSTRAINT PK_HISTORIAL_REPORTE PRIMARY KEY (ID_HISTORIAL)
);
