CREATE TABLE MUNICIPIOS (
    CODIGO_MUNICIPIO NUMBER(3) CONSTRAINT PK_MUNICIPIOS PRIMARY KEY,
    NOMBRE           VARCHAR2(60) CONSTRAINT NN_MUNICIPIOS_NOMBRE NOT NULL,
    CONSTRAINT UK_MUNICIPIOS_NOMBRE UNIQUE (NOMBRE)
);

INSERT ALL
INTO MUNICIPIOS VALUES (1,'ABEJORRAL')
INTO MUNICIPIOS VALUES (2,'ABRIAQUI')
INTO MUNICIPIOS VALUES (3,'ALEJANDRIA')
INTO MUNICIPIOS VALUES (4,'AMAGA')
INTO MUNICIPIOS VALUES (5,'AMALFI')
INTO MUNICIPIOS VALUES (6,'ANDES')
INTO MUNICIPIOS VALUES (7,'ANGELOPOLIS')
INTO MUNICIPIOS VALUES (8,'ANGOSTURA')
INTO MUNICIPIOS VALUES (9,'ANORI')
INTO MUNICIPIOS VALUES (10,'ANZA')
INTO MUNICIPIOS VALUES (11,'APARTADO')
INTO MUNICIPIOS VALUES (12,'ARBOLETES')
INTO MUNICIPIOS VALUES (13,'ARGELIA')
INTO MUNICIPIOS VALUES (14,'ARMENIA')
INTO MUNICIPIOS VALUES (15,'BARBOSA')
INTO MUNICIPIOS VALUES (16,'BELLO')
INTO MUNICIPIOS VALUES (17,'BELMIRA')
INTO MUNICIPIOS VALUES (18,'BETANIA')
INTO MUNICIPIOS VALUES (19,'BETULIA')
INTO MUNICIPIOS VALUES (20,'BRICEÑO')
INTO MUNICIPIOS VALUES (21,'BURITICA')
INTO MUNICIPIOS VALUES (22,'CACERES')
INTO MUNICIPIOS VALUES (23,'CAICEDO')
INTO MUNICIPIOS VALUES (24,'CALDAS')
INTO MUNICIPIOS VALUES (25,'CAMPAMENTO')
INTO MUNICIPIOS VALUES (26,'CAÑASGORDAS')
INTO MUNICIPIOS VALUES (27,'CARACOLI')
INTO MUNICIPIOS VALUES (28,'CARAMANTA')
INTO MUNICIPIOS VALUES (29,'CAREPA')
INTO MUNICIPIOS VALUES (30,'CAROLINA DEL PRINCIPE')
INTO MUNICIPIOS VALUES (31,'CAUCASIA')
INTO MUNICIPIOS VALUES (32,'CHIGORODO')
INTO MUNICIPIOS VALUES (33,'CISNEROS')
INTO MUNICIPIOS VALUES (34,'CIUDAD BOLIVAR')
INTO MUNICIPIOS VALUES (35,'COCORNA')
INTO MUNICIPIOS VALUES (36,'CONCEPCION')
INTO MUNICIPIOS VALUES (37,'CONCORDIA')
INTO MUNICIPIOS VALUES (38,'COPACABANA')
INTO MUNICIPIOS VALUES (39,'DABEIBA')
INTO MUNICIPIOS VALUES (40,'DON MATIAS')
INTO MUNICIPIOS VALUES (41,'EBEJICO')
INTO MUNICIPIOS VALUES (42,'EL BAGRE')
INTO MUNICIPIOS VALUES (43,'EL CARMEN DE VIBORAL')
INTO MUNICIPIOS VALUES (44,'EL PEÑOL')
INTO MUNICIPIOS VALUES (45,'EL RETIRO')
INTO MUNICIPIOS VALUES (46,'EL SANTUARIO')
INTO MUNICIPIOS VALUES (47,'ENTRERRIOS')
INTO MUNICIPIOS VALUES (48,'ENVIGADO')
INTO MUNICIPIOS VALUES (49,'FREDONIA')
INTO MUNICIPIOS VALUES (50,'FRONTINO')
INTO MUNICIPIOS VALUES (51,'GIRALDO')
INTO MUNICIPIOS VALUES (52,'GIRARDOTA')
INTO MUNICIPIOS VALUES (53,'GOMEZ PLATA')
INTO MUNICIPIOS VALUES (54,'GRANADA')
INTO MUNICIPIOS VALUES (55,'GUADALUPE')
INTO MUNICIPIOS VALUES (56,'GUARNE')
INTO MUNICIPIOS VALUES (57,'GUATAPE')
INTO MUNICIPIOS VALUES (58,'HELICONIA')
INTO MUNICIPIOS VALUES (59,'HISPANIA')
INTO MUNICIPIOS VALUES (60,'ITAGÜÍ')
INTO MUNICIPIOS VALUES (61,'ITUANGO')
INTO MUNICIPIOS VALUES (62,'JARDIN')
INTO MUNICIPIOS VALUES (63,'JERICO')
INTO MUNICIPIOS VALUES (64,'LA CEJA')
INTO MUNICIPIOS VALUES (65,'LA ESTRELLA')
INTO MUNICIPIOS VALUES (66,'LA PINTADA')
INTO MUNICIPIOS VALUES (67,'LA UNION')
INTO MUNICIPIOS VALUES (68,'LIBORINA')
INTO MUNICIPIOS VALUES (69,'MACEO')
INTO MUNICIPIOS VALUES (70,'MARINILLA')
INTO MUNICIPIOS VALUES (71,'MEDELLÍN')
INTO MUNICIPIOS VALUES (72,'MONTEBELLO')
INTO MUNICIPIOS VALUES (73,'MURINDO')
INTO MUNICIPIOS VALUES (74,'MUTATA')
INTO MUNICIPIOS VALUES (75,'NARIÑO')
INTO MUNICIPIOS VALUES (76,'NECHI')
INTO MUNICIPIOS VALUES (77,'NECOCLI')
INTO MUNICIPIOS VALUES (78,'OLAYA')
INTO MUNICIPIOS VALUES (79,'PEQUE')
INTO MUNICIPIOS VALUES (80,'PUEBLORRICO')
INTO MUNICIPIOS VALUES (81,'PUERTO BERRIO')
INTO MUNICIPIOS VALUES (82,'PUERTO NARE')
INTO MUNICIPIOS VALUES (83,'PUERTO TRIUNFO')
INTO MUNICIPIOS VALUES (84,'REMEDIOS')
INTO MUNICIPIOS VALUES (85,'RIONEGRO')
INTO MUNICIPIOS VALUES (86,'SABANALARGA')
INTO MUNICIPIOS VALUES (87,'SABANETA')
INTO MUNICIPIOS VALUES (88,'SALGAR')
INTO MUNICIPIOS VALUES (89,'SAN ANDRES DE CUERQUIA')
INTO MUNICIPIOS VALUES (90,'SAN CARLOS')
INTO MUNICIPIOS VALUES (91,'SAN FRANCISCO')
INTO MUNICIPIOS VALUES (92,'SAN JERONIMO')
INTO MUNICIPIOS VALUES (93,'SAN JOSE DE LA MONTAÑA')
INTO MUNICIPIOS VALUES (94,'SAN JUAN DE URABA')
INTO MUNICIPIOS VALUES (95,'SAN LUIS')
INTO MUNICIPIOS VALUES (96,'SAN PEDRO DE LOS MILAGROS')
INTO MUNICIPIOS VALUES (97,'SAN PEDRO DE URABA')
INTO MUNICIPIOS VALUES (98,'SAN RAFAEL')
INTO MUNICIPIOS VALUES (99,'SAN ROQUE')
INTO MUNICIPIOS VALUES (100,'SAN VICENTE')
INTO MUNICIPIOS VALUES (101,'SANTA BARBARA')
INTO MUNICIPIOS VALUES (102,'SANTA FE DE ANTIOQUIA')
INTO MUNICIPIOS VALUES (103,'SANTA ROSA DE OSOS')
INTO MUNICIPIOS VALUES (104,'SANTO DOMINGO')
INTO MUNICIPIOS VALUES (105,'SEGOVIA')
INTO MUNICIPIOS VALUES (106,'SONSON')
INTO MUNICIPIOS VALUES (107,'SOPETRAN')
INTO MUNICIPIOS VALUES (108,'TAMESIS')
INTO MUNICIPIOS VALUES (109,'TARAZA')
INTO MUNICIPIOS VALUES (110,'TARSO')
INTO MUNICIPIOS VALUES (111,'TITIRIBI')
INTO MUNICIPIOS VALUES (112,'TOLEDO')
INTO MUNICIPIOS VALUES (113,'TURBO')
INTO MUNICIPIOS VALUES (114,'URAMITA')
INTO MUNICIPIOS VALUES (115,'URRAO')
INTO MUNICIPIOS VALUES (116,'VALDIVIA')
INTO MUNICIPIOS VALUES (117,'VALPARAISO')
INTO MUNICIPIOS VALUES (118,'VEGACHI')
INTO MUNICIPIOS VALUES (119,'VENECIA')
INTO MUNICIPIOS VALUES (120,'VIGIA DEL FUERTE')
INTO MUNICIPIOS VALUES (121,'YALI')
INTO MUNICIPIOS VALUES (122,'YARUMAL')
INTO MUNICIPIOS VALUES (123,'YOLOMBÓ')
INTO MUNICIPIOS VALUES (124,'YONDO')
INTO MUNICIPIOS VALUES (125,'ZARAGOZA')
SELECT * FROM DUAL;

CREATE TABLE TIPO_ESTABLECIMIENTO (
    CODIGO_TIPO_ESTABLECIMIENTO NUMBER(2)
        CONSTRAINT PK_TIPO_ESTABLECIMIENTO PRIMARY KEY,
    NOMBRE VARCHAR2(100)
        CONSTRAINT NN_TIPO_ESTABLECIMIENTO_NOMBRE NOT NULL,
    CONSTRAINT UK_TIPO_ESTABLECIMIENTO_NOMBRE UNIQUE (NOMBRE)
);

INSERT ALL
    INTO TIPO_ESTABLECIMIENTO VALUES (1,'DROGUERÍA')
    INTO TIPO_ESTABLECIMIENTO VALUES (2,'FARMACIA-DROGUERÍA')
    INTO TIPO_ESTABLECIMIENTO VALUES (3,'SERVICIO FARMACÉUTICO')
    INTO TIPO_ESTABLECIMIENTO VALUES (4,'DEPÓSITO DE DROGAS')
    INTO TIPO_ESTABLECIMIENTO VALUES (5,'GESTOR FARMACÉUTICO')
    INTO TIPO_ESTABLECIMIENTO VALUES (6,'FARMACIA HOMEOPÁTICA')
    INTO TIPO_ESTABLECIMIENTO VALUES (7,'TIENDA NATURISTA')
    INTO TIPO_ESTABLECIMIENTO VALUES (8,'ESTABLECIMIENTO VETERINARIO')
    INTO TIPO_ESTABLECIMIENTO VALUES (9,'PRESTADOR DE SERVICIOS DE SALUD SIN SERVICIO FARMACÉUTICO')
    INTO TIPO_ESTABLECIMIENTO VALUES (10,'COMERCIALIZADOR DE DISPOSITIVOS MÉDICOS')
    INTO TIPO_ESTABLECIMIENTO VALUES (11,'AGENCIA DE ESPECIALIDADES FARMACÉUTICAS')
SELECT * FROM DUAL;

CREATE TABLE REGIONES (
    CODIGO_REGION NUMBER(2)
        CONSTRAINT PK_REGIONES PRIMARY KEY,
    NOMBRE VARCHAR2(50)
        CONSTRAINT NN_REGIONES_NOMBRE NOT NULL,
    CONSTRAINT UK_REGIONES_NOMBRE UNIQUE (NOMBRE)
);

INSERT ALL
    INTO REGIONES VALUES (1,'BAJO CAUCA')
    INTO REGIONES VALUES (2,'MAGDALENA MEDIO')
    INTO REGIONES VALUES (3,'NORDESTE')
    INTO REGIONES VALUES (4,'NORTE')
    INTO REGIONES VALUES (5,'OCCIDENTE')
    INTO REGIONES VALUES (6,'ORIENTE')
    INTO REGIONES VALUES (7,'SUROESTE')
    INTO REGIONES VALUES (8,'URABÁ')
    INTO REGIONES VALUES (9,'VALLE DE ABURRÁ')
SELECT * FROM DUAL;

CREATE TABLE ESTADOS_ESTABLECIMIENTO (
    CODIGO_ESTADO NUMBER(2)
        CONSTRAINT PK_ESTADOS_ESTABLECIMIENTO PRIMARY KEY,
    NOMBRE VARCHAR2(30)
        CONSTRAINT NN_ESTADOS_NOMBRE NOT NULL,
    CONSTRAINT UK_ESTADOS_NOMBRE UNIQUE (NOMBRE)
);

INSERT ALL
    INTO ESTADOS_ESTABLECIMIENTO VALUES (1,'ACTIVO')
    INTO ESTADOS_ESTABLECIMIENTO VALUES (2,'INACTIVO')    
SELECT * FROM DUAL;

CREATE TABLE GRUPOS_ESTABLECIMIENTO (

    CODIGO_GRUPO NUMBER(1)
        CONSTRAINT PK_GRUPOS_ESTABLECIMIENTO PRIMARY KEY,

    NOMBRE VARCHAR2(20)
        CONSTRAINT NN_GRUPOS_NOMBRE NOT NULL,

    CONSTRAINT UK_GRUPOS_NOMBRE UNIQUE (NOMBRE)

);

INSERT ALL
    INTO GRUPOS_ESTABLECIMIENTO VALUES (1,'MINORISTA')
    INTO GRUPOS_ESTABLECIMIENTO VALUES (2,'MAYORISTA')
SELECT * FROM DUAL;

CREATE TABLE TITULOS_DIRECTOR_TECNICO (

    CODIGO_TITULO NUMBER(2)
        CONSTRAINT PK_TITULOS_DIRECTOR PRIMARY KEY,

    NOMBRE VARCHAR2(120)
        CONSTRAINT NN_TITULOS_DIRECTOR_NOMBRE NOT NULL,

    CONSTRAINT UK_TITULOS_DIRECTOR_NOMBRE UNIQUE (NOMBRE)

);

INSERT ALL
    INTO TITULOS_DIRECTOR_TECNICO VALUES (1,'QUÍMICO FARMACÉUTICO')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (2,'REGENTE DE FARMACIA')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (3,'EXPENDEDOR DE DROGAS')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (4,'PERSONAL CON ENTRENAMIENTO EN MANEJO DE PRODUCTOS NATURALES O TIENDAS NATURISTAS')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (5,'MÉDICO')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (6,'MÉDICO VETERINARIO')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (7,'MÉDICO VETERINARIO ZOOTECNISTA')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (8,'ENFERMERO(A)')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (9,'OTRO PERFIL DEL ÁREA ASISTENCIAL')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (10,'PERSONAL CON FORMACIÓN RELACIONADA CON DISPOSITIVOS MÉDICOS')
SELECT * FROM DUAL;

CREATE TABLE TITULO_TIPO_ESTABLECIMIENTO (

    CODIGO_TIPO_ESTABLECIMIENTO NUMBER(2)
        CONSTRAINT FK_TTE_TIPO
        REFERENCES TIPO_ESTABLECIMIENTO(CODIGO_TIPO_ESTABLECIMIENTO),

    CODIGO_TITULO NUMBER(2)
        CONSTRAINT FK_TTE_TITULO
        REFERENCES TITULOS_DIRECTOR_TECNICO(CODIGO_TITULO),

    CONSTRAINT PK_TITULO_TIPO_ESTABLECIMIENTO
        PRIMARY KEY (CODIGO_TIPO_ESTABLECIMIENTO, CODIGO_TITULO)

);

INSERT ALL

-- DROGUERÍA
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (1,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (1,2)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (1,3)

-- FARMACIA-DROGUERÍA
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (2,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (2,2)

-- SERVICIO FARMACÉUTICO
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (3,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (3,2)

-- DEPÓSITO DE DROGAS
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (4,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (4,2)

-- GESTOR FARMACÉUTICO
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (5,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (5,2)

-- FARMACIA HOMEOPÁTICA
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (6,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (6,2)

-- TIENDA NATURISTA
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (7,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (7,2)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (7,4)

-- ESTABLECIMIENTO VETERINARIO
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (8,6)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (8,7)

-- PRESTADOR DE SERVICIOS DE SALUD SIN SERVICIO FARMACÉUTICO
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (9,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (9,2)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (9,5)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (9,8)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (9,9)

-- COMERCIALIZADOR DE DISPOSITIVOS MÉDICOS
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (10,1)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (10,2)
INTO TITULO_TIPO_ESTABLECIMIENTO VALUES (10,10)

SELECT * FROM DUAL;

CREATE TABLE ESTABLECIMIENTOS (

    CODIGO_ESTABLECIMIENTO VARCHAR2(20)
        CONSTRAINT PK_ESTABLECIMIENTOS PRIMARY KEY,

    CODIGO_GRUPO NUMBER(1)
        CONSTRAINT FK_EST_GRUPO
        REFERENCES GRUPOS_ESTABLECIMIENTO (CODIGO_GRUPO),

    CODIGO_TIPO_ESTABLECIMIENTO NUMBER(2)
        CONSTRAINT FK_EST_TIPO
        REFERENCES TIPO_ESTABLECIMIENTO (CODIGO_TIPO_ESTABLECIMIENTO),

    CODIGO_REGION NUMBER(2)
        CONSTRAINT FK_EST_REGION
        REFERENCES REGIONES (CODIGO_REGION),

    CODIGO_MUNICIPIO NUMBER(3)
        CONSTRAINT FK_EST_MUNICIPIO
        REFERENCES MUNICIPIOS (CODIGO_MUNICIPIO),

    RAZON_SOCIAL VARCHAR2(200)
        CONSTRAINT NN_EST_RAZON_SOCIAL NOT NULL,

    DIRECCION VARCHAR2(250),

    BARRIO VARCHAR2(100),

    TELEFONOS VARCHAR2(200),

    ID_DT VARCHAR2(20),

    NOMBRE_DIRECTOR_TECNICO VARCHAR2(200),

    CODIGO_TITULO NUMBER(2)
        CONSTRAINT FK_EST_TITULO_DT
        REFERENCES TITULOS_DIRECTOR_TECNICO (CODIGO_TITULO),

    ID_PROPIETARIO VARCHAR2(20),

    NOMBRE_PROPIETARIO VARCHAR2(200),

    ID_RL VARCHAR2(20),

    NOMBRE_REPRESENTANTE VARCHAR2(200),

    MATRICULA_MERCANTIL VARCHAR2(30),

    NIT VARCHAR2(20)
        CONSTRAINT UK_EST_NIT UNIQUE,

    EMAIL VARCHAR2(150)
        CONSTRAINT CK_EST_EMAIL
        CHECK (EMAIL IS NULL OR EMAIL LIKE '%@%.%'),

    CODIGO_ESTADO NUMBER(1)
        CONSTRAINT FK_EST_ESTADO
        REFERENCES ESTADOS_ESTABLECIMIENTO (CODIGO_ESTADO),

    FECHA_CREACION DATE DEFAULT SYSDATE,

    USUARIO_CREACION VARCHAR2(50),

    FECHA_ULTIMA_ACTUALIZACION DATE DEFAULT SYSDATE,

    USUARIO_ULTIMA_ACTUALIZACION VARCHAR2(50),

    ID_ULTIMA_NOVEDAD NUMBER,

    OBSERVACIONES VARCHAR2(500)

);

ALTER TABLE ESTABLECIMIENTOS ADD (

    INYECTOLOGIA           CHAR(1) DEFAULT 'N'
        CONSTRAINT CK_EST_INYECTOLOGIA
        CHECK (INYECTOLOGIA IN ('S','N')),

    MCE                    CHAR(1) DEFAULT 'N'
        CONSTRAINT CK_EST_MCE
        CHECK (MCE IN ('S','N')),

    EAPB                   CHAR(1) DEFAULT 'N'
        CONSTRAINT CK_EST_EAPB
        CHECK (EAPB IN ('S','N')),

    VENTAS_A_DISTANCIA     CHAR(1) DEFAULT 'N'
        CONSTRAINT CK_EST_VENTAS_DISTANCIA
        CHECK (VENTAS_A_DISTANCIA IN ('S','N')),

    TOMA_GLICEMIA          CHAR(1) DEFAULT 'N'
        CONSTRAINT CK_EST_TOMA_GLICEMIA
        CHECK (TOMA_GLICEMIA IN ('S','N'))

);

ALTER TABLE ESTABLECIMIENTOS ADD (
    MAGISTRALES CHAR(1) DEFAULT 'N'
        CONSTRAINT CK_EST_MAGISTRALES
        CHECK (MAGISTRALES IN ('S','N'))
);

BEGIN

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD, CODIGO_TIPO_ESTABLECIMIENTO)
SELECT 3, CODIGO_TIPO_ESTABLECIMIENTO
FROM TIPO_ESTABLECIMIENTO;

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD, CODIGO_TIPO_ESTABLECIMIENTO)
SELECT 4, CODIGO_TIPO_ESTABLECIMIENTO
FROM TIPO_ESTABLECIMIENTO;

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD, CODIGO_TIPO_ESTABLECIMIENTO)
SELECT 5, CODIGO_TIPO_ESTABLECIMIENTO
FROM TIPO_ESTABLECIMIENTO;

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD, CODIGO_TIPO_ESTABLECIMIENTO)
SELECT 6, CODIGO_TIPO_ESTABLECIMIENTO
FROM TIPO_ESTABLECIMIENTO;

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD, CODIGO_TIPO_ESTABLECIMIENTO)
SELECT 7, CODIGO_TIPO_ESTABLECIMIENTO
FROM TIPO_ESTABLECIMIENTO;

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD, CODIGO_TIPO_ESTABLECIMIENTO)
SELECT 8, CODIGO_TIPO_ESTABLECIMIENTO
FROM TIPO_ESTABLECIMIENTO;

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD, CODIGO_TIPO_ESTABLECIMIENTO)
SELECT 14, CODIGO_TIPO_ESTABLECIMIENTO
FROM TIPO_ESTABLECIMIENTO;

COMMIT;

END;
/

CREATE TABLE TIPOS_NOVEDAD (
    ID_TIPO_NOVEDAD      NUMBER GENERATED BY DEFAULT AS IDENTITY
                         PRIMARY KEY,
    CODIGO               NUMBER(2) NOT NULL,
    TIPO_NOVEDAD         VARCHAR2(200) NOT NULL,
    ACTUALIZA_CENSO      CHAR(1) DEFAULT 'N'
                         CHECK (ACTUALIZA_CENSO IN ('S','N')),
    ACTIVO               CHAR(1) DEFAULT 'S'
                         CHECK (ACTIVO IN ('S','N'))
);


BEGIN

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (1,'CAMBIO DE DIRECTOR TÉCNICO O RESPONSABLE DEL ESTABLECIMIENTO','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (2,'VACACIONES DEL DIRECTOR TÉCNICO O RESPONSABLE DEL ESTABLECIMIENTO','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (3,'CAMBIO DE RAZÓN SOCIAL','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (4,'CAMBIO DE PROPIETARIO','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (5,'CAMBIO DE TELÉFONO','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (6,'CAMBIO DE CORREO ELECTRÓNICO','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (7,'CIERRE TEMPORAL','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (8,'CIERRE DEFINITIVO','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (9,'SUSPENSIÓN DE SERVICIOS','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (10,'MODIFICACIÓN DEL HORARIO DE ATENCIÓN','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (11,'CAMBIO DE NIVEL DE COMPLEJIDAD','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (12,'CAMBIO DE RESPONSABLE DEL MANEJO DE MEDICAMENTOS DE CONTROL ESPECIAL','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (13,'NOVEDAD RELACIONADA CON MEDICAMENTOS DE CONTROL ESPECIAL','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (14,'OTRA NOVEDAD','N','S');

    COMMIT;

END;
/

CREATE TABLE ESTADOS_REPORTE (
    ID_ESTADO_REPORTE    NUMBER GENERATED BY DEFAULT AS IDENTITY
                         PRIMARY KEY,
    NOMBRE_ESTADO        VARCHAR2(50) NOT NULL,
    DESCRIPCION          VARCHAR2(300),
    ACTIVO               CHAR(1) DEFAULT 'S'
                         CHECK (ACTIVO IN ('S','N'))
);

BEGIN

    INSERT INTO ESTADOS_REPORTE
    (NOMBRE_ESTADO, ACTIVO)
    VALUES
    ('RADICADO','S');

    INSERT INTO ESTADOS_REPORTE
    (NOMBRE_ESTADO, ACTIVO)
    VALUES
    ('APLICADO AL CENSO','S');

    INSERT INTO ESTADOS_REPORTE
    (NOMBRE_ESTADO, ACTIVO)
    VALUES
    ('NOTIFICADO','S');

    COMMIT;

END;
/

CREATE TABLE CAMPOS_NOVEDAD (

    ID_CAMPO NUMBER GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_CAMPOS_NOVEDAD PRIMARY KEY,

    ETIQUETA VARCHAR2(100)
        CONSTRAINT NN_CAMPOS_NOVEDAD_ETIQUETA NOT NULL,

    TIPO_DATO VARCHAR2(20)
        CONSTRAINT NN_CAMPOS_NOVEDAD_TIPO NOT NULL
        CONSTRAINT CK_CAMPOS_NOVEDAD_TIPO
        CHECK (TIPO_DATO IN (
            'TEXTO',
            'TEXTO_LARGO',
            'NUMERO',
            'FECHA',
            'EMAIL',
            'TELEFONO',
            'LISTA'
        )),

    ACTIVO CHAR(1) DEFAULT 'S'
        CONSTRAINT CK_CAMPOS_NOVEDAD_ACTIVO
        CHECK (ACTIVO IN ('S','N')),

    CONSTRAINT UK_CAMPOS_NOVEDAD_ETIQUETA
        UNIQUE (ETIQUETA)

);

BEGIN

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NOMBRE DEL DIRECTOR TÉCNICO','TEXTO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('DOCUMENTO DEL DIRECTOR TÉCNICO','NUMERO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('PERFIL DEL DIRECTOR TÉCNICO','LISTA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('OBSERVACIONES','TEXTO_LARGO','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('FECHA INICIO','FECHA','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('FECHA FIN','FECHA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NOMBRE DEL SUSTITUTO','TEXTO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('DOCUMENTO DEL SUSTITUTO','NUMERO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('PERFIL DEL SUSTITUTO','LISTA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NUEVA RAZÓN SOCIAL','TEXTO','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NOMBRE DEL PROPIETARIO','TEXTO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('DOCUMENTO DEL PROPIETARIO','NUMERO','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NUEVO NÚMERO TELEFÓNICO','TELEFONO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NUEVO CORREO ELECTRÓNICO','EMAIL','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('FECHA DE CIERRE','FECHA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('SERVICIO','LISTA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('HORARIO DE ATENCIÓN','TEXTO','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NIVEL DE COMPLEJIDAD','LISTA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NOMBRE DEL RESPONSABLE MCE','TEXTO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('DOCUMENTO DEL RESPONSABLE MCE','NUMERO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('PERFIL DEL RESPONSABLE MCE','LISTA','S');

COMMIT;

END;
/

CREATE TABLE TIPO_NOVEDAD_ESTABLECIMIENTO (
    ID_TIPO_NOVEDAD_ESTABLECIMIENTO NUMBER GENERATED BY DEFAULT AS IDENTITY
                                    PRIMARY KEY,

    ID_TIPO_NOVEDAD                 NUMBER NOT NULL,

    CODIGO_TIPO_ESTABLECIMIENTO     NUMBER(2) NOT NULL,

    CONSTRAINT FK_TNE_TIPO_NOVEDAD
        FOREIGN KEY (ID_TIPO_NOVEDAD)
        REFERENCES TIPOS_NOVEDAD(ID_TIPO_NOVEDAD),

    CONSTRAINT FK_TNE_TIPO_ESTABLECIMIENTO
        FOREIGN KEY (CODIGO_TIPO_ESTABLECIMIENTO)
        REFERENCES TIPO_ESTABLECIMIENTO(CODIGO_TIPO_ESTABLECIMIENTO),

    CONSTRAINT UK_TNE
        UNIQUE (
            ID_TIPO_NOVEDAD,
            CODIGO_TIPO_ESTABLECIMIENTO
        )
);

BEGIN

/* ===========================
   NOVEDAD 1
=========================== */

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (1,2);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (1,3);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (1,7);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (1,10);

/* ===========================
   NOVEDAD 2
=========================== */

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (2,1);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (2,2);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (2,3);

/* ===========================
   NOVEDAD 9
=========================== */

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (9,1);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (9,2);

/* ===========================
   NOVEDAD 10
=========================== */

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (10,1);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (10,2);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (10,3);

/* ===========================
   NOVEDAD 11
=========================== */

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (11,3);

/* ===========================
   NOVEDAD 12
=========================== */

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (12,1);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (12,2);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (12,3);

/* ===========================
   NOVEDAD 13
=========================== */

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (13,1);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (13,2);

INSERT INTO TIPO_NOVEDAD_ESTABLECIMIENTO
(ID_TIPO_NOVEDAD,CODIGO_TIPO_ESTABLECIMIENTO)
VALUES (13,3);

COMMIT;

END;
/

CREATE TABLE SERVICIOS (

    CODIGO_SERVICIO NUMBER(2)
        CONSTRAINT PK_SERVICIOS PRIMARY KEY,

    NOMBRE VARCHAR2(100)
        CONSTRAINT NN_SERVICIOS_NOMBRE NOT NULL,

    CAMPO_CENSO VARCHAR2(30)
        CONSTRAINT NN_SERVICIOS_COLUMNA NOT NULL,

    ACTIVO CHAR(1) DEFAULT 'S'
        CONSTRAINT CK_SERVICIOS_ACTIVO
        CHECK (ACTIVO IN ('S','N')),

    CONSTRAINT UK_SERVICIOS_NOMBRE
        UNIQUE (NOMBRE),

    CONSTRAINT UK_SERVICIOS_COLUMNA
        UNIQUE (CAMPO_CENSO)

);

INSERT ALL

INTO SERVICIOS VALUES
(1,'INYECTOLOGÍA','INYECTOLOGIA','S')

INTO SERVICIOS VALUES
(2,'MEDICAMENTOS DE CONTROL ESPECIAL','MCE','S')

INTO SERVICIOS VALUES
(3,'ATENCIÓN EAPB','EAPB','S')

INTO SERVICIOS VALUES
(4,'VENTAS A DISTANCIA','VENTAS_A_DISTANCIA','S')

INTO SERVICIOS VALUES
(5,'TOMA DE GLICEMIA POR PUNCIÓN','TOMA_GLICEMIA','S')

INTO SERVICIOS VALUES
(6,'PREPARACIONES MAGISTRALES','MAGISTRALES','S')

SELECT * FROM DUAL;


CREATE TABLE TIPO_NOVEDAD_CAMPOS (
    ID_TIPO_NOVEDAD_CAMPO  NUMBER GENERATED BY DEFAULT AS IDENTITY
                           PRIMARY KEY,

    ID_TIPO_NOVEDAD        NUMBER NOT NULL,

    ID_CAMPO               NUMBER NOT NULL,

    OBLIGATORIO            CHAR(1) DEFAULT 'N'
                           CHECK (OBLIGATORIO IN ('S','N')),

    ACTUALIZA_CENSO        CHAR(1) DEFAULT 'N'
                           CHECK (ACTUALIZA_CENSO IN ('S','N')),

    ORDEN                  NUMBER(2) NOT NULL,

    CONSTRAINT FK_TNC_TIPO_NOVEDAD
        FOREIGN KEY (ID_TIPO_NOVEDAD)
        REFERENCES TIPOS_NOVEDAD (ID_TIPO_NOVEDAD),

    CONSTRAINT FK_TNC_CAMPO
        FOREIGN KEY (ID_CAMPO)
        REFERENCES CAMPOS_NOVEDAD (ID_CAMPO),

    CONSTRAINT UK_TNC
        UNIQUE (ID_TIPO_NOVEDAD, ID_CAMPO)
);

BEGIN

/*=========================================================
NOVEDAD 1 - CAMBIO DE DIRECTOR TÉCNICO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
(ID_TIPO_NOVEDAD,ID_CAMPO,OBLIGATORIO,ACTUALIZA_CENSO,ORDEN)
VALUES (1,1,'S','S',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,1,2,'S','S',2);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,1,3,'S','S',3);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,1,4,'N','N',4);

/*=========================================================
NOVEDAD 2 - VACACIONES DEL DIRECTOR TÉCNICO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,2,5,'S','N',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,2,6,'S','N',2);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,2,7,'S','N',3);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,2,8,'S','N',4);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,2,9,'S','N',5);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,2,4,'N','N',6);

/*=========================================================
NOVEDAD 3 - CAMBIO DE RAZÓN SOCIAL
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,3,10,'S','S',1);

/*=========================================================
NOVEDAD 4 - CAMBIO DE PROPIETARIO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,4,11,'S','S',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,4,12,'S','S',2);

/*=========================================================
NOVEDAD 5 - CAMBIO DE TELÉFONO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,5,13,'S','S',1);

/*=========================================================
NOVEDAD 6 - CAMBIO DE CORREO ELECTRÓNICO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,6,14,'S','S',1);

/*=========================================================
NOVEDAD 7 - CIERRE TEMPORAL
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,7,5,'S','N',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,7,6,'S','N',2);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,7,4,'N','N',3);

COMMIT;

END;
/

BEGIN

/*=========================================================
NOVEDAD 8 - CIERRE DEFINITIVO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,8,15,'S','N',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,8,4,'N','N',2);

/*=========================================================
NOVEDAD 9 - SUSPENSIÓN DE SERVICIO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,9,16,'S','S',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,9,4,'N','N',2);

/*=========================================================
NOVEDAD 10 - CAMBIO DE HORARIO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,10,17,'S','S',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,10,4,'N','N',2);

/*=========================================================
NOVEDAD 11 - CAMBIO DE NIVEL DE COMPLEJIDAD
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,11,18,'S','S',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,11,4,'N','N',2);

/*=========================================================
NOVEDAD 12 - CAMBIO DE RESPONSABLE MCE
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,12,19,'S','N',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,12,20,'S','N',2);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,12,21,'S','N',3);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,12,4,'N','N',4);

/*=========================================================
NOVEDAD 13 - ACTIVACIÓN DE SERVICIO
=========================================================*/

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,13,16,'S','S',1);

INSERT INTO TIPO_NOVEDAD_CAMPOS
VALUES (DEFAULT,13,4,'N','N',2);

COMMIT;

END;
/

CREATE TABLE TIPOS_REPORTANTE (

    CODIGO_TIPO_REPORTANTE NUMBER(1)
        CONSTRAINT PK_TIPOS_REPORTANTE PRIMARY KEY,

    NOMBRE VARCHAR2(50)
        CONSTRAINT NN_TIPOS_REPORTANTE_NOMBRE NOT NULL,

    CONSTRAINT UK_TIPOS_REPORTANTE_NOMBRE
        UNIQUE (NOMBRE)

);

INSERT ALL
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (1, 'DIRECTOR TÉCNICO')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (2, 'REPRESENTANTE LEGAL')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (3, 'PROPIETARIO')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (4, 'AUXILIAR')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (5, 'OTRO')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (6, 'FUNCIONARIO DSSA')
SELECT * FROM DUAL;


CREATE TABLE REPORTES (

    ID_REPORTE NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_REPORTES PRIMARY KEY,

    CODIGO_ESTABLECIMIENTO VARCHAR2(20)
        CONSTRAINT NN_REP_ESTABLECIMIENTO NOT NULL
        CONSTRAINT FK_REP_ESTABLECIMIENTO
            REFERENCES ESTABLECIMIENTOS (CODIGO_ESTABLECIMIENTO),

    ID_TIPO_NOVEDAD NUMBER
        CONSTRAINT NN_REP_TIPO_NOVEDAD NOT NULL
        CONSTRAINT FK_REP_TIPO_NOVEDAD
            REFERENCES TIPOS_NOVEDAD (ID_TIPO_NOVEDAD),

    ID_ESTADO_REPORTE NUMBER
        CONSTRAINT NN_REP_ESTADO NOT NULL
        CONSTRAINT FK_REP_ESTADO
            REFERENCES ESTADOS_REPORTE (ID_ESTADO_REPORTE),

    CODIGO_TIPO_REPORTANTE NUMBER(1)
        CONSTRAINT NN_REP_TIPO_REPORTANTE NOT NULL
        CONSTRAINT FK_REP_TIPO_REPORTANTE
            REFERENCES TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE),

    NOMBRE_REPORTANTE VARCHAR2(200)
        CONSTRAINT NN_REP_NOMBRE_REPORTANTE NOT NULL,

    DOCUMENTO_REPORTANTE VARCHAR2(20)
        CONSTRAINT NN_REP_DOCUMENTO_REPORTANTE NOT NULL,

    FECHA_REPORTE DATE
        DEFAULT SYSDATE
        CONSTRAINT NN_REP_FECHA_REPORTE NOT NULL,

    FECHA_NOTIFICACION DATE,

    OBSERVACIONES VARCHAR2(1000)

);

CREATE TABLE DETALLE_REPORTE (

    ID_DETALLE_REPORTE NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_DETALLE_REPORTE PRIMARY KEY,

    ID_REPORTE NUMBER
        CONSTRAINT NN_DR_REPORTE NOT NULL
        CONSTRAINT FK_DR_REPORTE
            REFERENCES REPORTES (ID_REPORTE),

    ID_TIPO_NOVEDAD_CAMPO NUMBER
        CONSTRAINT NN_DR_CAMPO NOT NULL
        CONSTRAINT FK_DR_CAMPO
            REFERENCES TIPO_NOVEDAD_CAMPOS (ID_TIPO_NOVEDAD_CAMPO),

    VALOR VARCHAR2(4000)
        CONSTRAINT NN_DR_VALOR NOT NULL

);

CREATE TABLE HISTORIAL_ACTUALIZACIONES (

    ID_HISTORIAL NUMBER
        GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT PK_HISTORIAL_ACTUALIZACIONES PRIMARY KEY,

    ID_REPORTE NUMBER
        CONSTRAINT NN_HIST_REPORTE NOT NULL
        CONSTRAINT FK_HIST_REPORTE
            REFERENCES REPORTES (ID_REPORTE),

    CODIGO_ESTABLECIMIENTO VARCHAR2(20)
        CONSTRAINT NN_HIST_ESTABLECIMIENTO NOT NULL
        CONSTRAINT FK_HIST_ESTABLECIMIENTO
            REFERENCES ESTABLECIMIENTOS (CODIGO_ESTABLECIMIENTO),

    ID_CAMPO NUMBER
        CONSTRAINT NN_HIST_CAMPO NOT NULL
        CONSTRAINT FK_HIST_CAMPO
            REFERENCES CAMPOS_NOVEDAD (ID_CAMPO),

    VALOR_ANTERIOR VARCHAR2(4000),

    VALOR_NUEVO VARCHAR2(4000)
        CONSTRAINT NN_HIST_VALOR_NUEVO NOT NULL,

    FECHA_ACTUALIZACION DATE
        DEFAULT SYSDATE
        CONSTRAINT NN_HIST_FECHA NOT NULL

);

CREATE TABLE CONCEPTOS_SANITARIOS (

    CODIGO_CONCEPTO_SANITARIO NUMBER(1)
        CONSTRAINT PK_CONCEPTOS_SANITARIOS PRIMARY KEY,

    NOMBRE VARCHAR2(50)
        CONSTRAINT NN_CONCEPTOS_SANITARIOS_NOMBRE NOT NULL,

    CONSTRAINT UK_CONCEPTOS_SANITARIOS_NOMBRE
        UNIQUE (NOMBRE)

);

INSERT ALL
    INTO CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO, NOMBRE)
        VALUES (1, 'FAVORABLE')

    INTO CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO, NOMBRE)
        VALUES (2, 'FAVORABLE CON REQUERIMIENTOS')

    INTO CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO, NOMBRE)
        VALUES (3, 'DESFAVORABLE')

    INTO CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO, NOMBRE)
        VALUES (4, 'SIN CONCEPTO')

SELECT * FROM DUAL;

ALTER TABLE ESTABLECIMIENTOS
ADD CODIGO_CONCEPTO_SANITARIO NUMBER(1);

ALTER TABLE ESTABLECIMIENTOS
ADD CONSTRAINT FK_EST_CONCEPTO_SANITARIO
FOREIGN KEY (CODIGO_CONCEPTO_SANITARIO)
REFERENCES CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO);



