/* =========================================================
   PROYECTO FRAMED
   Archivo: 02_constraints.sql
   Descripción: Llaves foráneas e integridad referencial
   Motor: Oracle Database
   ========================================================= */


/* =========================================================
   ESTABLECIMIENTO
   ========================================================= */

ALTER TABLE ESTABLECIMIENTO
    ADD CONSTRAINT FK_ESTABLECIMIENTO_MUNICIPIO
    FOREIGN KEY (MUNICIPIO)
    REFERENCES MUNICIPIOS (ID_MUNICIPIO);

ALTER TABLE ESTABLECIMIENTO
    ADD CONSTRAINT FK_ESTABLECIMIENTO_DT
    FOREIGN KEY (ID_DT)
    REFERENCES DT (ID_DT);

ALTER TABLE ESTABLECIMIENTO
    ADD CONSTRAINT FK_ESTABLECIMIENTO_ESTADO
    FOREIGN KEY (ID_ESTADO)
    REFERENCES ESTADO (ID_ESTADO);


/* =========================================================
   ESTABLECIMIENTO_SERVICIO
   ========================================================= */

ALTER TABLE ESTABLECIMIENTO_SERVICIO
    ADD CONSTRAINT FK_EST_SERV_ESTABLECIMIENTO
    FOREIGN KEY (ID_ESTABLECIMIENTO)
    REFERENCES ESTABLECIMIENTO (ID_ESTABLECIMIENTO);

ALTER TABLE ESTABLECIMIENTO_SERVICIO
    ADD CONSTRAINT FK_EST_SERV_SERVICIO
    FOREIGN KEY (ID_SERVICIO)
    REFERENCES SERVICIOS (ID_SERVICIO);


/* =========================================================
   REPORTES
   ========================================================= */

ALTER TABLE REPORTES
    ADD CONSTRAINT FK_REPORTES_ESTABLECIMIENTO
    FOREIGN KEY (ID_ESTABLECIMIENTO)
    REFERENCES ESTABLECIMIENTO (ID_ESTABLECIMIENTO);

ALTER TABLE REPORTES
    ADD CONSTRAINT FK_REPORTES_REPORTANTE
    FOREIGN KEY (ID_REPORTANTE)
    REFERENCES REPORTANTE (ID_REPORTANTE);

ALTER TABLE REPORTES
    ADD CONSTRAINT FK_REPORTES_ESTADO
    FOREIGN KEY (ID_ESTADO_REPORTE)
    REFERENCES ESTADO_REPORTE (ID_ESTADO_REPORTE);


/* =========================================================
   NOVEDADES
   ========================================================= */

ALTER TABLE NOVEDADES
    ADD CONSTRAINT FK_NOVEDADES_REPORTE
    FOREIGN KEY (ID_REPORTE)
    REFERENCES REPORTES (ID_REPORTE);

ALTER TABLE NOVEDADES
    ADD CONSTRAINT FK_NOVEDADES_ESTABLECIMIENTO
    FOREIGN KEY (ID_ESTABLECIMIENTO)
    REFERENCES ESTABLECIMIENTO (ID_ESTABLECIMIENTO);

ALTER TABLE NOVEDADES
    ADD CONSTRAINT FK_NOVEDADES_TIPO
    FOREIGN KEY (ID_TIPO_NOVEDAD)
    REFERENCES TIPO_NOVEDAD (ID_TIPO_NOVEDAD);


/* =========================================================
   HISTORIAL_REPORTE
   ========================================================= */

ALTER TABLE HISTORIAL_REPORTE
    ADD CONSTRAINT FK_HISTORIAL_REPORTE
    FOREIGN KEY (ID_REPORTE)
    REFERENCES REPORTES (ID_REPORTE);
