/* =========================================================
   PROYECTO FRAMED
   Archivo: 03_catalogos.sql
   Descripción: Carga de catálogos y datos maestros del modelo
                definitivo de FRAMED
   Motor: Oracle Database

   Importante:
   - Este archivo debe ejecutarse después de 01_creacion_tablas.sql
     y 02_constraints.sql.
   - No contiene relaciones entre catálogos; esas se organizan en
     04_relaciones_catalogos.sql.
   ========================================================= */


/* =========================================================
   1. DATOS DE MUNICIPIOS
   ========================================================= */

INSERT ALL
INTO MUNICIPIOS VALUES (1,'ABEJORRAL')
INTO MUNICIPIOS VALUES (2,'ABRIAQUI')
INTO MUNICIPIOS VALUES (3,'ALEJANDRIA')
INTO MUNICIPIOS VALUES (4,'AMAGA')
INTO MUNICIPIOS VALUES (5,'AMALFI')
INTO MUNICIPIOS VALUES (6,'ANDES')
INTO MUNICIPIOS VALUES (7,'ANGELOPOLIS')
INTO MUNICIPIOS VALUES (8,'ANGOSTURA')
INTO MUNICIPIOS VALUES (9,'ANORI')
INTO MUNICIPIOS VALUES (10,'ANZA')
INTO MUNICIPIOS VALUES (11,'APARTADO')
INTO MUNICIPIOS VALUES (12,'ARBOLETES')
INTO MUNICIPIOS VALUES (13,'ARGELIA')
INTO MUNICIPIOS VALUES (14,'ARMENIA')
INTO MUNICIPIOS VALUES (15,'BARBOSA')
INTO MUNICIPIOS VALUES (16,'BELLO')
INTO MUNICIPIOS VALUES (17,'BELMIRA')
INTO MUNICIPIOS VALUES (18,'BETANIA')
INTO MUNICIPIOS VALUES (19,'BETULIA')
INTO MUNICIPIOS VALUES (20,'BRICEÑO')
INTO MUNICIPIOS VALUES (21,'BURITICA')
INTO MUNICIPIOS VALUES (22,'CACERES')
INTO MUNICIPIOS VALUES (23,'CAICEDO')
INTO MUNICIPIOS VALUES (24,'CALDAS')
INTO MUNICIPIOS VALUES (25,'CAMPAMENTO')
INTO MUNICIPIOS VALUES (26,'CAÑASGORDAS')
INTO MUNICIPIOS VALUES (27,'CARACOLI')
INTO MUNICIPIOS VALUES (28,'CARAMANTA')
INTO MUNICIPIOS VALUES (29,'CAREPA')
INTO MUNICIPIOS VALUES (30,'CAROLINA DEL PRINCIPE')
INTO MUNICIPIOS VALUES (31,'CAUCASIA')
INTO MUNICIPIOS VALUES (32,'CHIGORODO')
INTO MUNICIPIOS VALUES (33,'CISNEROS')
INTO MUNICIPIOS VALUES (34,'CIUDAD BOLIVAR')
INTO MUNICIPIOS VALUES (35,'COCORNA')
INTO MUNICIPIOS VALUES (36,'CONCEPCION')
INTO MUNICIPIOS VALUES (37,'CONCORDIA')
INTO MUNICIPIOS VALUES (38,'COPACABANA')
INTO MUNICIPIOS VALUES (39,'DABEIBA')
INTO MUNICIPIOS VALUES (40,'DON MATIAS')
INTO MUNICIPIOS VALUES (41,'EBEJICO')
INTO MUNICIPIOS VALUES (42,'EL BAGRE')
INTO MUNICIPIOS VALUES (43,'EL CARMEN DE VIBORAL')
INTO MUNICIPIOS VALUES (44,'EL PEÑOL')
INTO MUNICIPIOS VALUES (45,'EL RETIRO')
INTO MUNICIPIOS VALUES (46,'EL SANTUARIO')
INTO MUNICIPIOS VALUES (47,'ENTRERRIOS')
INTO MUNICIPIOS VALUES (48,'ENVIGADO')
INTO MUNICIPIOS VALUES (49,'FREDONIA')
INTO MUNICIPIOS VALUES (50,'FRONTINO')
INTO MUNICIPIOS VALUES (51,'GIRALDO')
INTO MUNICIPIOS VALUES (52,'GIRARDOTA')
INTO MUNICIPIOS VALUES (53,'GOMEZ PLATA')
INTO MUNICIPIOS VALUES (54,'GRANADA')
INTO MUNICIPIOS VALUES (55,'GUADALUPE')
INTO MUNICIPIOS VALUES (56,'GUARNE')
INTO MUNICIPIOS VALUES (57,'GUATAPE')
INTO MUNICIPIOS VALUES (58,'HELICONIA')
INTO MUNICIPIOS VALUES (59,'HISPANIA')
INTO MUNICIPIOS VALUES (60,'ITAGÜÍ')
INTO MUNICIPIOS VALUES (61,'ITUANGO')
INTO MUNICIPIOS VALUES (62,'JARDIN')
INTO MUNICIPIOS VALUES (63,'JERICO')
INTO MUNICIPIOS VALUES (64,'LA CEJA')
INTO MUNICIPIOS VALUES (65,'LA ESTRELLA')
INTO MUNICIPIOS VALUES (66,'LA PINTADA')
INTO MUNICIPIOS VALUES (67,'LA UNION')
INTO MUNICIPIOS VALUES (68,'LIBORINA')
INTO MUNICIPIOS VALUES (69,'MACEO')
INTO MUNICIPIOS VALUES (70,'MARINILLA')
INTO MUNICIPIOS VALUES (71,'MEDELLÍN')
INTO MUNICIPIOS VALUES (72,'MONTEBELLO')
INTO MUNICIPIOS VALUES (73,'MURINDO')
INTO MUNICIPIOS VALUES (74,'MUTATA')
INTO MUNICIPIOS VALUES (75,'NARIÑO')
INTO MUNICIPIOS VALUES (76,'NECHI')
INTO MUNICIPIOS VALUES (77,'NECOCLI')
INTO MUNICIPIOS VALUES (78,'OLAYA')
INTO MUNICIPIOS VALUES (79,'PEQUE')
INTO MUNICIPIOS VALUES (80,'PUEBLORRICO')
INTO MUNICIPIOS VALUES (81,'PUERTO BERRIO')
INTO MUNICIPIOS VALUES (82,'PUERTO NARE')
INTO MUNICIPIOS VALUES (83,'PUERTO TRIUNFO')
INTO MUNICIPIOS VALUES (84,'REMEDIOS')
INTO MUNICIPIOS VALUES (85,'RIONEGRO')
INTO MUNICIPIOS VALUES (86,'SABANALARGA')
INTO MUNICIPIOS VALUES (87,'SABANETA')
INTO MUNICIPIOS VALUES (88,'SALGAR')
INTO MUNICIPIOS VALUES (89,'SAN ANDRES DE CUERQUIA')
INTO MUNICIPIOS VALUES (90,'SAN CARLOS')
INTO MUNICIPIOS VALUES (91,'SAN FRANCISCO')
INTO MUNICIPIOS VALUES (92,'SAN JERONIMO')
INTO MUNICIPIOS VALUES (93,'SAN JOSE DE LA MONTAÑA')
INTO MUNICIPIOS VALUES (94,'SAN JUAN DE URABA')
INTO MUNICIPIOS VALUES (95,'SAN LUIS')
INTO MUNICIPIOS VALUES (96,'SAN PEDRO DE LOS MILAGROS')
INTO MUNICIPIOS VALUES (97,'SAN PEDRO DE URABA')
INTO MUNICIPIOS VALUES (98,'SAN RAFAEL')
INTO MUNICIPIOS VALUES (99,'SAN ROQUE')
INTO MUNICIPIOS VALUES (100,'SAN VICENTE')
INTO MUNICIPIOS VALUES (101,'SANTA BARBARA')
INTO MUNICIPIOS VALUES (102,'SANTA FE DE ANTIOQUIA')
INTO MUNICIPIOS VALUES (103,'SANTA ROSA DE OSOS')
INTO MUNICIPIOS VALUES (104,'SANTO DOMINGO')
INTO MUNICIPIOS VALUES (105,'SEGOVIA')
INTO MUNICIPIOS VALUES (106,'SONSON')
INTO MUNICIPIOS VALUES (107,'SOPETRAN')
INTO MUNICIPIOS VALUES (108,'TAMESIS')
INTO MUNICIPIOS VALUES (109,'TARAZA')
INTO MUNICIPIOS VALUES (110,'TARSO')
INTO MUNICIPIOS VALUES (111,'TITIRIBI')
INTO MUNICIPIOS VALUES (112,'TOLEDO')
INTO MUNICIPIOS VALUES (113,'TURBO')
INTO MUNICIPIOS VALUES (114,'URAMITA')
INTO MUNICIPIOS VALUES (115,'URRAO')
INTO MUNICIPIOS VALUES (116,'VALDIVIA')
INTO MUNICIPIOS VALUES (117,'VALPARAISO')
INTO MUNICIPIOS VALUES (118,'VEGACHI')
INTO MUNICIPIOS VALUES (119,'VENECIA')
INTO MUNICIPIOS VALUES (120,'VIGIA DEL FUERTE')
INTO MUNICIPIOS VALUES (121,'YALI')
INTO MUNICIPIOS VALUES (122,'YARUMAL')
INTO MUNICIPIOS VALUES (123,'YOLOMBÓ')
INTO MUNICIPIOS VALUES (124,'YONDO')
INTO MUNICIPIOS VALUES (125,'ZARAGOZA')
SELECT * FROM DUAL;


/* =========================================================
   2. DATOS DE TIPO_ESTABLECIMIENTO
   ========================================================= */

INSERT ALL
    INTO TIPO_ESTABLECIMIENTO VALUES (1,'DROGUERÍA')
    INTO TIPO_ESTABLECIMIENTO VALUES (2,'FARMACIA-DROGUERÍA')
    INTO TIPO_ESTABLECIMIENTO VALUES (3,'SERVICIO FARMACÉUTICO')
    INTO TIPO_ESTABLECIMIENTO VALUES (4,'DEPÓSITO DE DROGAS')
    INTO TIPO_ESTABLECIMIENTO VALUES (5,'GESTOR FARMACÉUTICO')
    INTO TIPO_ESTABLECIMIENTO VALUES (6,'FARMACIA HOMEOPÁTICA')
    INTO TIPO_ESTABLECIMIENTO VALUES (7,'TIENDA NATURISTA')
    INTO TIPO_ESTABLECIMIENTO VALUES (8,'ESTABLECIMIENTO VETERINARIO')
    INTO TIPO_ESTABLECIMIENTO VALUES (9,'PRESTADOR DE SERVICIOS DE SALUD SIN SERVICIO FARMACÉUTICO')
    INTO TIPO_ESTABLECIMIENTO VALUES (10,'COMERCIALIZADOR DE DISPOSITIVOS MÉDICOS')
    INTO TIPO_ESTABLECIMIENTO VALUES (11,'AGENCIA DE ESPECIALIDADES FARMACÉUTICAS')
SELECT * FROM DUAL;


/* =========================================================
   3. DATOS DE REGIONES
   ========================================================= */

INSERT ALL
    INTO REGIONES VALUES (1,'BAJO CAUCA')
    INTO REGIONES VALUES (2,'MAGDALENA MEDIO')
    INTO REGIONES VALUES (3,'NORDESTE')
    INTO REGIONES VALUES (4,'NORTE')
    INTO REGIONES VALUES (5,'OCCIDENTE')
    INTO REGIONES VALUES (6,'ORIENTE')
    INTO REGIONES VALUES (7,'SUROESTE')
    INTO REGIONES VALUES (8,'URABÁ')
    INTO REGIONES VALUES (9,'VALLE DE ABURRÁ')
SELECT * FROM DUAL;


/* =========================================================
   4. DATOS DE ESTADOS_ESTABLECIMIENTO
   ========================================================= */

INSERT ALL
    INTO ESTADOS_ESTABLECIMIENTO VALUES (1,'ACTIVO')
    INTO ESTADOS_ESTABLECIMIENTO VALUES (2,'INACTIVO')    
SELECT * FROM DUAL;


/* =========================================================
   5. DATOS DE GRUPOS_ESTABLECIMIENTO
   ========================================================= */

INSERT ALL
    INTO GRUPOS_ESTABLECIMIENTO VALUES (1,'MINORISTA')
    INTO GRUPOS_ESTABLECIMIENTO VALUES (2,'MAYORISTA')
SELECT * FROM DUAL;


/* =========================================================
   6. DATOS DE TITULOS_DIRECTOR_TECNICO
   ========================================================= */

INSERT ALL
    INTO TITULOS_DIRECTOR_TECNICO VALUES (1,'QUÍMICO FARMACÉUTICO')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (2,'REGENTE DE FARMACIA')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (3,'EXPENDEDOR DE DROGAS')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (4,'PERSONAL CON ENTRENAMIENTO EN MANEJO DE PRODUCTOS NATURALES O TIENDAS NATURISTAS')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (5,'MÉDICO')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (6,'MÉDICO VETERINARIO')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (7,'MÉDICO VETERINARIO ZOOTECNISTA')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (8,'ENFERMERO(A)')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (9,'OTRO PERFIL DEL ÁREA ASISTENCIAL')
    INTO TITULOS_DIRECTOR_TECNICO VALUES (10,'PERSONAL CON FORMACIÓN RELACIONADA CON DISPOSITIVOS MÉDICOS')
SELECT * FROM DUAL;


/* =========================================================
   7. DATOS DE TIPOS_NOVEDAD
   ========================================================= */

BEGIN

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (1,'CAMBIO DE DIRECTOR TÉCNICO O RESPONSABLE DEL ESTABLECIMIENTO','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (2,'VACACIONES DEL DIRECTOR TÉCNICO O RESPONSABLE DEL ESTABLECIMIENTO','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (3,'CAMBIO DE RAZÓN SOCIAL','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (4,'CAMBIO DE PROPIETARIO','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (5,'CAMBIO DE TELÉFONO','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (6,'CAMBIO DE CORREO ELECTRÓNICO','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (7,'CIERRE TEMPORAL','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (8,'CIERRE DEFINITIVO','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (9,'SUSPENSIÓN DE SERVICIOS','S','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (10,'MODIFICACIÓN DEL HORARIO DE ATENCIÓN','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (11,'CAMBIO DE NIVEL DE COMPLEJIDAD','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (12,'CAMBIO DE RESPONSABLE DEL MANEJO DE MEDICAMENTOS DE CONTROL ESPECIAL','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (13,'NOVEDAD RELACIONADA CON MEDICAMENTOS DE CONTROL ESPECIAL','N','S');

    INSERT INTO TIPOS_NOVEDAD
    (CODIGO, TIPO_NOVEDAD, ACTUALIZA_CENSO, ACTIVO)
    VALUES (14,'OTRA NOVEDAD','N','S');

    COMMIT;

END;
/


/* =========================================================
   8. DATOS DE ESTADOS_REPORTE
   ========================================================= */

BEGIN

    INSERT INTO ESTADOS_REPORTE
    (NOMBRE_ESTADO, ACTIVO)
    VALUES
    ('RADICADO','S');

    INSERT INTO ESTADOS_REPORTE
    (NOMBRE_ESTADO, ACTIVO)
    VALUES
    ('APLICADO AL CENSO','S');

    INSERT INTO ESTADOS_REPORTE
    (NOMBRE_ESTADO, ACTIVO)
    VALUES
    ('NOTIFICADO','S');

    COMMIT;

END;
/


/* =========================================================
   9. DATOS DE CAMPOS_NOVEDAD
   ========================================================= */

BEGIN

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NOMBRE DEL DIRECTOR TÉCNICO','TEXTO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('DOCUMENTO DEL DIRECTOR TÉCNICO','NUMERO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('PERFIL DEL DIRECTOR TÉCNICO','LISTA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('OBSERVACIONES','TEXTO_LARGO','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('FECHA INICIO','FECHA','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('FECHA FIN','FECHA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NOMBRE DEL SUSTITUTO','TEXTO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('DOCUMENTO DEL SUSTITUTO','NUMERO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('PERFIL DEL SUSTITUTO','LISTA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NUEVA RAZÓN SOCIAL','TEXTO','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NOMBRE DEL PROPIETARIO','TEXTO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('DOCUMENTO DEL PROPIETARIO','NUMERO','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NUEVO NÚMERO TELEFÓNICO','TELEFONO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NUEVO CORREO ELECTRÓNICO','EMAIL','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('FECHA DE CIERRE','FECHA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('SERVICIO','LISTA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('HORARIO DE ATENCIÓN','TEXTO','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NIVEL DE COMPLEJIDAD','LISTA','S');

INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('NOMBRE DEL RESPONSABLE MCE','TEXTO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('DOCUMENTO DEL RESPONSABLE MCE','NUMERO','S');
INSERT INTO CAMPOS_NOVEDAD (ETIQUETA,TIPO_DATO,ACTIVO) VALUES ('PERFIL DEL RESPONSABLE MCE','LISTA','S');

COMMIT;

END;
/


/* =========================================================
   10. DATOS DE SERVICIOS
   ========================================================= */

INSERT ALL

INTO SERVICIOS VALUES
(1,'INYECTOLOGÍA','INYECTOLOGIA','S')

INTO SERVICIOS VALUES
(2,'MEDICAMENTOS DE CONTROL ESPECIAL','MCE','S')

INTO SERVICIOS VALUES
(3,'ATENCIÓN EAPB','EAPB','S')

INTO SERVICIOS VALUES
(4,'VENTAS A DISTANCIA','VENTAS_A_DISTANCIA','S')

INTO SERVICIOS VALUES
(5,'TOMA DE GLICEMIA POR PUNCIÓN','TOMA_GLICEMIA','S')

INTO SERVICIOS VALUES
(6,'PREPARACIONES MAGISTRALES','MAGISTRALES','S')

SELECT * FROM DUAL;


/* =========================================================
   11. DATOS DE TIPOS_REPORTANTE
   ========================================================= */

INSERT ALL
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (1, 'DIRECTOR TÉCNICO')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (2, 'REPRESENTANTE LEGAL')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (3, 'PROPIETARIO')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (4, 'AUXILIAR')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (5, 'OTRO')
    INTO TIPOS_REPORTANTE (CODIGO_TIPO_REPORTANTE, NOMBRE) VALUES (6, 'FUNCIONARIO DSSA')
SELECT * FROM DUAL;


/* =========================================================
   12. DATOS DE CONCEPTOS_SANITARIOS
   ========================================================= */

INSERT ALL
    INTO CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO, NOMBRE)
        VALUES (1, 'FAVORABLE')

    INTO CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO, NOMBRE)
        VALUES (2, 'FAVORABLE CON REQUERIMIENTOS')

    INTO CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO, NOMBRE)
        VALUES (3, 'DESFAVORABLE')

    INTO CONCEPTOS_SANITARIOS (CODIGO_CONCEPTO_SANITARIO, NOMBRE)
        VALUES (4, 'SIN CONCEPTO')

SELECT * FROM DUAL;


/* =========================================================
   FIN DEL SCRIPT DE CATÁLOGOS
   ========================================================= */
