/* =========================================================
   PROYECTO FRAMED
   Archivo: 08_seguridad.sql
   Descripción: Roles y permisos para el modelo definitivo
                de FRAMED
   Motor: Oracle Database

   Importante:
   - Este script debe ejecutarse con un usuario que tenga
     privilegios para crear roles y otorgar permisos.
   - Los roles se crean solo si no existen.
   - La autenticación de usuarios finales puede gestionarse
     adicionalmente desde Oracle APEX.
   ========================================================= */


/* =========================================================
   1. CREACIÓN DE ROLES
   ========================================================= */

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE FRAMED_ADMIN';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE FRAMED_GESTOR';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'CREATE ROLE FRAMED_CONSULTA';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1921 THEN
            RAISE;
        END IF;
END;
/


/* =========================================================
   2. PERMISOS DEL ROL ADMINISTRADOR
   ========================================================= */

GRANT SELECT, INSERT, UPDATE, DELETE ON MUNICIPIOS
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TIPO_ESTABLECIMIENTO
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON REGIONES
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON ESTADOS_ESTABLECIMIENTO
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON GRUPOS_ESTABLECIMIENTO
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TITULOS_DIRECTOR_TECNICO
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TITULO_TIPO_ESTABLECIMIENTO
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON ESTABLECIMIENTOS
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TIPOS_NOVEDAD
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON ESTADOS_REPORTE
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON CAMPOS_NOVEDAD
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TIPO_NOVEDAD_ESTABLECIMIENTO
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON SERVICIOS
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TIPO_NOVEDAD_CAMPOS
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON TIPOS_REPORTANTE
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON REPORTES
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON DETALLE_REPORTE
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON HISTORIAL_ACTUALIZACIONES
TO FRAMED_ADMIN;

GRANT SELECT, INSERT, UPDATE, DELETE ON CONCEPTOS_SANITARIOS
TO FRAMED_ADMIN;


/* =========================================================
   3. PERMISOS DEL ROL GESTOR
   ========================================================= */

GRANT SELECT ON MUNICIPIOS TO FRAMED_GESTOR;
GRANT SELECT ON TIPO_ESTABLECIMIENTO TO FRAMED_GESTOR;
GRANT SELECT ON REGIONES TO FRAMED_GESTOR;
GRANT SELECT ON ESTADOS_ESTABLECIMIENTO TO FRAMED_GESTOR;
GRANT SELECT ON GRUPOS_ESTABLECIMIENTO TO FRAMED_GESTOR;
GRANT SELECT ON TITULOS_DIRECTOR_TECNICO TO FRAMED_GESTOR;
GRANT SELECT ON TITULO_TIPO_ESTABLECIMIENTO TO FRAMED_GESTOR;
GRANT SELECT ON TIPOS_NOVEDAD TO FRAMED_GESTOR;
GRANT SELECT ON ESTADOS_REPORTE TO FRAMED_GESTOR;
GRANT SELECT ON CAMPOS_NOVEDAD TO FRAMED_GESTOR;
GRANT SELECT ON TIPO_NOVEDAD_ESTABLECIMIENTO TO FRAMED_GESTOR;
GRANT SELECT ON SERVICIOS TO FRAMED_GESTOR;
GRANT SELECT ON TIPO_NOVEDAD_CAMPOS TO FRAMED_GESTOR;
GRANT SELECT ON TIPOS_REPORTANTE TO FRAMED_GESTOR;
GRANT SELECT ON CONCEPTOS_SANITARIOS TO FRAMED_GESTOR;

GRANT SELECT, INSERT, UPDATE ON ESTABLECIMIENTOS
TO FRAMED_GESTOR;

GRANT SELECT, INSERT, UPDATE ON REPORTES
TO FRAMED_GESTOR;

GRANT SELECT, INSERT, UPDATE ON DETALLE_REPORTE
TO FRAMED_GESTOR;

GRANT SELECT, INSERT ON HISTORIAL_ACTUALIZACIONES
TO FRAMED_GESTOR;


/* =========================================================
   4. PERMISOS DEL ROL DE CONSULTA
   ========================================================= */

GRANT SELECT ON MUNICIPIOS TO FRAMED_CONSULTA;
GRANT SELECT ON TIPO_ESTABLECIMIENTO TO FRAMED_CONSULTA;
GRANT SELECT ON REGIONES TO FRAMED_CONSULTA;
GRANT SELECT ON ESTADOS_ESTABLECIMIENTO TO FRAMED_CONSULTA;
GRANT SELECT ON GRUPOS_ESTABLECIMIENTO TO FRAMED_CONSULTA;
GRANT SELECT ON TITULOS_DIRECTOR_TECNICO TO FRAMED_CONSULTA;
GRANT SELECT ON ESTABLECIMIENTOS TO FRAMED_CONSULTA;
GRANT SELECT ON TIPOS_NOVEDAD TO FRAMED_CONSULTA;
GRANT SELECT ON ESTADOS_REPORTE TO FRAMED_CONSULTA;
GRANT SELECT ON SERVICIOS TO FRAMED_CONSULTA;
GRANT SELECT ON TIPOS_REPORTANTE TO FRAMED_CONSULTA;
GRANT SELECT ON REPORTES TO FRAMED_CONSULTA;
GRANT SELECT ON DETALLE_REPORTE TO FRAMED_CONSULTA;
GRANT SELECT ON HISTORIAL_ACTUALIZACIONES TO FRAMED_CONSULTA;
GRANT SELECT ON CONCEPTOS_SANITARIOS TO FRAMED_CONSULTA;


/* =========================================================
   5. PERMISOS SOBRE VISTAS
   ========================================================= */

GRANT SELECT ON VW_ESTABLECIMIENTOS_COMPLETOS
TO FRAMED_ADMIN, FRAMED_GESTOR, FRAMED_CONSULTA;

GRANT SELECT ON VW_REPORTES_COMPLETOS
TO FRAMED_ADMIN, FRAMED_GESTOR, FRAMED_CONSULTA;

GRANT SELECT ON VW_DETALLE_NOVEDADES
TO FRAMED_ADMIN, FRAMED_GESTOR, FRAMED_CONSULTA;

GRANT SELECT ON VW_HISTORIAL_ACTUALIZACIONES
TO FRAMED_ADMIN, FRAMED_GESTOR, FRAMED_CONSULTA;

GRANT SELECT ON VW_INDICADORES_GENERALES
TO FRAMED_ADMIN, FRAMED_GESTOR, FRAMED_CONSULTA;

GRANT SELECT ON VW_ESTABLECIMIENTOS_POR_MUNICIPIO
TO FRAMED_ADMIN, FRAMED_GESTOR, FRAMED_CONSULTA;


/* =========================================================
   6. PERMISOS SOBRE PROCEDIMIENTOS
   ========================================================= */

GRANT EXECUTE ON SP_REGISTRAR_ESTABLECIMIENTO
TO FRAMED_ADMIN, FRAMED_GESTOR;

GRANT EXECUTE ON SP_ACTUALIZAR_CONTACTO_EST
TO FRAMED_ADMIN, FRAMED_GESTOR;

GRANT EXECUTE ON SP_REGISTRAR_REPORTE
TO FRAMED_ADMIN, FRAMED_GESTOR;

GRANT EXECUTE ON SP_REGISTRAR_DETALLE_REPORTE
TO FRAMED_ADMIN, FRAMED_GESTOR;

GRANT EXECUTE ON SP_CAMBIAR_ESTADO_REPORTE
TO FRAMED_ADMIN, FRAMED_GESTOR;

GRANT EXECUTE ON SP_REGISTRAR_HISTORIAL
TO FRAMED_ADMIN, FRAMED_GESTOR;


/* =========================================================
   7. EJEMPLO DE ASIGNACIÓN DE ROLES

   Sustituir los nombres de usuario por cuentas reales:

   GRANT FRAMED_ADMIN TO USUARIO_ADMIN;
   GRANT FRAMED_GESTOR TO USUARIO_GESTOR;
   GRANT FRAMED_CONSULTA TO USUARIO_CONSULTA;
   ========================================================= */


/* =========================================================
   FIN DEL SCRIPT DE SEGURIDAD
   ========================================================= */
