/* =========================================================
   PROYECTO FRAMED
   Archivo: 08_seguridad.sql
   Descripción: Seguridad
   ========================================================= */


/* ROLES */

CREATE ROLE FRAMED_ADMIN;

CREATE ROLE FRAMED_CONSULTA;


/* PERMISOS */

GRANT SELECT,INSERT,UPDATE,DELETE
ON ESTABLECIMIENTO
TO FRAMED_ADMIN;

GRANT SELECT
ON ESTABLECIMIENTO
TO FRAMED_CONSULTA;

GRANT SELECT
ON REPORTES
TO FRAMED_CONSULTA;

GRANT SELECT
ON NOVEDADES
TO FRAMED_CONSULTA;
